$ANSIBLE_VAULT;1.1;AES256
38393639343133393661363162353432653131626663383662303739383262636236313035653666
6365666664323562616461343861366564333130613337660a623630383433313234666534663637
33356332383838643438343035303464373337346338343239313733623338643665626333326136
3232643935343836640a383634646134616664313438333436333963366565323664663738656333
34626163666265373134623537633932613632343064653661666139353763663937343164333834
66333832313463636636326338646338613466363662333131386638346239663162626437306436
61613164366333653436643562386638316661356262626433393539383833623938366135333965
63313337666662326137383630643334393238316662353939623563353332333163383432636631
65303337656165613566303630393437366136373035386361623835613731306137303638363534
6139346538613630366462333766656335313835396661663638
